# The name of this file shouldn't be changed, or else the Setup Assistant won't detect it
# To use 3D LiDAR instead of realsense camera --> /scan_3D, padding_offset = 0.01, max_range=3.0
sensors:
  - filtered_cloud_topic: filtered_cloud
    max_range: 5.0
    max_update_rate: 10.0
    padding_offset: 0.1
    padding_scale: 1.0
    point_cloud_topic: /camera/depth/color/points
    point_subsample: 1
    sensor_plugin: occupancy_map_monitor/PointCloudOctomapUpdater
