// Generated by gencpp from file web_joystick_control/JoystickData.msg
// DO NOT EDIT!


#ifndef WEB_JOYSTICK_CONTROL_MESSAGE_JOYSTICKDATA_H
#define WEB_JOYSTICK_CONTROL_MESSAGE_JOYSTICKDATA_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace web_joystick_control
{
template <class ContainerAllocator>
struct JoystickData_
{
  typedef JoystickData_<ContainerAllocator> Type;

  JoystickData_()
    : stamp()
    , axes()
    , buttons()  {
    }
  JoystickData_(const ContainerAllocator& _alloc)
    : stamp()
    , axes(_alloc)
    , buttons(_alloc)  {
  (void)_alloc;
    }



   typedef ros::Time _stamp_type;
  _stamp_type stamp;

   typedef std::vector<float, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<float>> _axes_type;
  _axes_type axes;

   typedef std::vector<int32_t, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<int32_t>> _buttons_type;
  _buttons_type buttons;





  typedef boost::shared_ptr< ::web_joystick_control::JoystickData_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::web_joystick_control::JoystickData_<ContainerAllocator> const> ConstPtr;

}; // struct JoystickData_

typedef ::web_joystick_control::JoystickData_<std::allocator<void> > JoystickData;

typedef boost::shared_ptr< ::web_joystick_control::JoystickData > JoystickDataPtr;
typedef boost::shared_ptr< ::web_joystick_control::JoystickData const> JoystickDataConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::web_joystick_control::JoystickData_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::web_joystick_control::JoystickData_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::web_joystick_control::JoystickData_<ContainerAllocator1> & lhs, const ::web_joystick_control::JoystickData_<ContainerAllocator2> & rhs)
{
  return lhs.stamp == rhs.stamp &&
    lhs.axes == rhs.axes &&
    lhs.buttons == rhs.buttons;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::web_joystick_control::JoystickData_<ContainerAllocator1> & lhs, const ::web_joystick_control::JoystickData_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace web_joystick_control

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::web_joystick_control::JoystickData_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::web_joystick_control::JoystickData_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::web_joystick_control::JoystickData_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::web_joystick_control::JoystickData_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::web_joystick_control::JoystickData_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::web_joystick_control::JoystickData_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::web_joystick_control::JoystickData_<ContainerAllocator> >
{
  static const char* value()
  {
    return "850b4f36c57999e6c2ba9e1c61f93ee3";
  }

  static const char* value(const ::web_joystick_control::JoystickData_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x850b4f36c57999e6ULL;
  static const uint64_t static_value2 = 0xc2ba9e1c61f93ee3ULL;
};

template<class ContainerAllocator>
struct DataType< ::web_joystick_control::JoystickData_<ContainerAllocator> >
{
  static const char* value()
  {
    return "web_joystick_control/JoystickData";
  }

  static const char* value(const ::web_joystick_control::JoystickData_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::web_joystick_control::JoystickData_<ContainerAllocator> >
{
  static const char* value()
  {
    return "time stamp\n"
"float32[] axes\n"
"int32[] buttons\n"
;
  }

  static const char* value(const ::web_joystick_control::JoystickData_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::web_joystick_control::JoystickData_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.stamp);
      stream.next(m.axes);
      stream.next(m.buttons);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct JoystickData_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::web_joystick_control::JoystickData_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::web_joystick_control::JoystickData_<ContainerAllocator>& v)
  {
    s << indent << "stamp: ";
    Printer<ros::Time>::stream(s, indent + "  ", v.stamp);
    s << indent << "axes[]" << std::endl;
    for (size_t i = 0; i < v.axes.size(); ++i)
    {
      s << indent << "  axes[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.axes[i]);
    }
    s << indent << "buttons[]" << std::endl;
    for (size_t i = 0; i < v.buttons.size(); ++i)
    {
      s << indent << "  buttons[" << i << "]: ";
      Printer<int32_t>::stream(s, indent + "  ", v.buttons[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // WEB_JOYSTICK_CONTROL_MESSAGE_JOYSTICKDATA_H
